In [46]:
!pip install --upgrade pip
!pip install --upgrade matplotlib seaborn
!pip install ydata-profiling
!pip install --upgrade jupyter ipywidgets

Requirement already satisfied: pip in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (24.0)
Collecting pip
  Using cached pip-24.2-py3-none-any.whl.metadata (3.6 kB)
Using cached pip-24.2-py3-none-any.whl (1.8 MB)

WARNING: Ignoring invalid distribution -atplotlib (c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages)
ERROR: To modify pip, please run the following command:
C:\Users\jazpi\anaconda3\envs\machinelearning\python.exe -m pip install --upgrade pip

Requirement already satisfied: matplotlib in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (3.9.2)
Requirement already satisfied: seaborn in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (0.13.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from matplotlib) (1.2.1)
Requirement already satisfied: cycler>=0.10 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from matplotlib) (4.53.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from matplotlib) (1.4.5)
Requirement already satisfied: numpy>=1.23 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from matplotlib) (1.26.4)
Requirement already satisfied: packaging>=20.0 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from matplotlib) (24.1)
Requirement already satisfied: pillow>=8 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from matplotlib) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from matplotlib) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from matplotlib) (2.9.0)
Requirement already satisfied: pandas>=1.2 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from seaborn) (2.2.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from pandas>=1.2->seaborn) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from pandas>=1.2->seaborn) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)

WARNING: Ignoring invalid distribution -atplotlib (c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages)

Requirement already satisfied: ydata-profiling in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (4.9.0)

WARNING: Ignoring invalid distribution -atplotlib (c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages)
WARNING: visions 0.7.6 does not provide the extra 'type-image-path'
WARNING: Ignoring invalid distribution -atplotlib (c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages)

Requirement already satisfied: scipy<1.14,>=1.4.1 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from ydata-profiling) (1.13.1)
Requirement already satisfied: pandas!=1.4.0,<3,>1.1 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from ydata-profiling) (2.2.2)
Requirement already satisfied: matplotlib<3.10,>=3.5 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from ydata-profiling) (3.9.2)
Requirement already satisfied: pydantic>=2 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from ydata-profiling) (2.8.2)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from ydata-profiling) (6.0.2)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from ydata-profiling) (3.1.4)
Requirement already satisfied: visions<0.7.7,>=0.7.5 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from visions[type_image_path]<0.7.7,>=0.7.5->ydata-profiling) (0.7.6)
Requirement already satisfied: numpy<2,>=1.16.0 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from ydata-profiling) (1.26.4)
Requirement already satisfied: htmlmin==0.1.12 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from ydata-profiling) (0.1.12)
Requirement already satisfied: phik<0.13,>=0.11.1 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from ydata-profiling) (0.12.4)
Requirement already satisfied: requests<3,>=2.24.0 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from ydata-profiling) (2.32.3)
Requirement already satisfied: tqdm<5,>=4.48.2 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from ydata-profiling) (4.66.4)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from ydata-profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from ydata-profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from ydata-profiling) (0.14.2)
Requirement already satisfied: typeguard<5,>=3 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from ydata-profiling) (4.3.0)
Requirement already satisfied: imagehash==4.3.1 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from ydata-profiling) (4.3.1)
Requirement already satisfied: wordcloud>=1.9.1 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from ydata-profiling) (1.9.3)
Requirement already satisfied: dacite>=1.8 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from ydata-profiling) (1.8.1)
Requirement already satisfied: numba<1,>=0.56.0 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from ydata-profiling) (0.60.0)
Requirement already satisfied: PyWavelets in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from imagehash==4.3.1->ydata-profiling) (1.7.0)
Requirement already satisfied: pillow in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from imagehash==4.3.1->ydata-profiling) (10.4.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from jinja2<3.2,>=2.11.1->ydata-profiling) (2.1.5)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from matplotlib<3.10,>=3.5->ydata-profiling) (1.2.1)
Requirement already satisfied: cycler>=0.10 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from matplotlib<3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from matplotlib<3.10,>=3.5->ydata-profiling) (4.53.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from matplotlib<3.10,>=3.5->ydata-profiling) (1.4.5)
Requirement already satisfied: packaging>=20.0 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from matplotlib<3.10,>=3.5->ydata-profiling) (24.1)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from matplotlib<3.10,>=3.5->ydata-profiling) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from matplotlib<3.10,>=3.5->ydata-profiling) (2.9.0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from numba<1,>=0.56.0->ydata-profiling) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from pandas!=1.4.0,<3,>1.1->ydata-profiling) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from pandas!=1.4.0,<3,>1.1->ydata-profiling) (2024.1)
Requirement already satisfied: joblib>=0.14.1 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from phik<0.13,>=0.11.1->ydata-profiling) (1.4.2)
Requirement already satisfied: annotated-types>=0.4.0 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from pydantic>=2->ydata-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.20.1 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from pydantic>=2->ydata-profiling) (2.20.1)
Requirement already satisfied: typing-extensions>=4.6.1 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from pydantic>=2->ydata-profiling) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from requests<3,>=2.24.0->ydata-profiling) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from requests<3,>=2.24.0->ydata-profiling) (3.8)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from requests<3,>=2.24.0->ydata-profiling) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from requests<3,>=2.24.0->ydata-profiling) (2024.7.4)
Requirement already satisfied: patsy>=0.5.6 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (0.5.6)
Requirement already satisfied: colorama in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from tqdm<5,>=4.48.2->ydata-profiling) (0.4.6)
Requirement already satisfied: attrs>=19.3.0 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from visions<0.7.7,>=0.7.5->visions[type_image_path]<0.7.7,>=0.7.5->ydata-profiling) (24.2.0)
Requirement already satisfied: networkx>=2.4 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from visions<0.7.7,>=0.7.5->visions[type_image_path]<0.7.7,>=0.7.5->ydata-profiling) (3.3)
Requirement already satisfied: six in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from patsy>=0.5.6->statsmodels<1,>=0.13.2->ydata-profiling) (1.16.0)
Requirement already satisfied: jupyter in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (1.0.0)
Requirement already satisfied: ipywidgets in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (8.1.5)
Requirement already satisfied: notebook in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from jupyter) (7.2.1)
Requirement already satisfied: qtconsole in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from jupyter) (5.5.2)
Requirement already satisfied: jupyter-console in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from jupyter) (6.6.3)
Requirement already satisfied: nbconvert in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from jupyter) (7.16.4)
Requirement already satisfied: ipykernel in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from jupyter) (6.29.4)
Requirement already satisfied: comm>=0.1.3 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from ipywidgets) (0.2.2)
Requirement already satisfied: ipython>=6.1.0 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from ipywidgets) (8.26.0)
Requirement already satisfied: traitlets>=4.3.1 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from ipywidgets) (5.14.3)
Requirement already satisfied: widgetsnbextension~=4.0.12 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from ipywidgets) (4.0.13)
Requirement already satisfied: jupyterlab-widgets~=3.0.12 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from ipywidgets) (3.0.13)
Requirement already satisfied: decorator in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from ipython>=6.1.0->ipywidgets) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.19.1)
Requirement already satisfied: matplotlib-inline in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.1.7)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from ipython>=6.1.0->ipywidgets) (3.0.47)
Requirement already satisfied: pygments>=2.4.0 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from ipython>=6.1.0->ipywidgets) (2.18.0)
Requirement already satisfied: stack-data in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.6.2)
Requirement already satisfied: exceptiongroup in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from ipython>=6.1.0->ipywidgets) (1.2.0)
Requirement already satisfied: typing-extensions>=4.6 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from ipython>=6.1.0->ipywidgets) (4.12.2)
Requirement already satisfied: colorama in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.4.6)
Requirement already satisfied: debugpy>=1.6.5 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from ipykernel->jupyter) (1.8.2)
Requirement already satisfied: jupyter-client>=6.1.12 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from ipykernel->jupyter) (8.6.2)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from ipykernel->jupyter) (5.7.2)
Requirement already satisfied: nest-asyncio in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from ipykernel->jupyter) (1.6.0)
Requirement already satisfied: packaging in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from ipykernel->jupyter) (24.1)
Requirement already satisfied: psutil in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from ipykernel->jupyter) (6.0.0)
Requirement already satisfied: pyzmq>=24 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from ipykernel->jupyter) (26.0.3)
Requirement already satisfied: tornado>=6.1 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from ipykernel->jupyter) (6.4.1)
Requirement already satisfied: beautifulsoup4 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from nbconvert->jupyter) (4.12.3)
Requirement already satisfied: bleach!=5.0.0 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from nbconvert->jupyter) (6.1.0)
Requirement already satisfied: defusedxml in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from nbconvert->jupyter) (0.7.1)
Requirement already satisfied: jinja2>=3.0 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from nbconvert->jupyter) (3.1.4)
Requirement already satisfied: jupyterlab-pygments in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from nbconvert->jupyter) (0.3.0)
Requirement already satisfied: markupsafe>=2.0 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from nbconvert->jupyter) (2.1.5)
Requirement already satisfied: mistune<4,>=2.0.3 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from nbconvert->jupyter) (3.0.2)
Requirement already satisfied: nbclient>=0.5.0 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from nbconvert->jupyter) (0.10.0)
Requirement already satisfied: nbformat>=5.7 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from nbconvert->jupyter) (5.10.4)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from nbconvert->jupyter) (1.5.1)
Requirement already satisfied: tinycss2 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from nbconvert->jupyter) (1.3.0)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from notebook->jupyter) (2.14.2)
Requirement already satisfied: jupyterlab-server<3,>=2.27.1 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from notebook->jupyter) (2.27.3)
Requirement already satisfied: jupyterlab<4.3,>=4.2.0 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from notebook->jupyter) (4.2.4)
Requirement already satisfied: notebook-shim<0.3,>=0.2 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from notebook->jupyter) (0.2.4)
Requirement already satisfied: qtpy>=2.4.0 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from qtconsole->jupyter) (2.4.1)
Requirement already satisfied: six>=1.9.0 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from bleach!=5.0.0->nbconvert->jupyter) (1.16.0)
Requirement already satisfied: webencodings in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from bleach!=5.0.0->nbconvert->jupyter) (0.5.1)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets) (0.8.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from jupyter-client>=6.1.12->ipykernel->jupyter) (2.9.0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel->jupyter) (4.2.2)
Requirement already satisfied: pywin32>=300 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel->jupyter) (306)
Requirement already satisfied: anyio>=3.1.0 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (4.4.0)
Requirement already satisfied: argon2-cffi>=21.1 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (23.1.0)
Requirement already satisfied: jupyter-events>=0.9.0 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (0.10.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (0.5.3)
Requirement already satisfied: overrides>=5.0 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (7.7.0)
Requirement already satisfied: prometheus-client>=0.9 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (0.20.0)
Requirement already satisfied: pywinpty>=2.0.1 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (2.0.13)
Requirement already satisfied: send2trash>=1.8.2 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (1.8.3)
Requirement already satisfied: terminado>=0.8.3 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (0.18.1)
Requirement already satisfied: websocket-client>=1.7 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (1.8.0)
Requirement already satisfied: async-lru>=1.0.0 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from jupyterlab<4.3,>=4.2.0->notebook->jupyter) (2.0.4)
Requirement already satisfied: httpx>=0.25.0 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from jupyterlab<4.3,>=4.2.0->notebook->jupyter) (0.27.0)
Requirement already satisfied: jupyter-lsp>=2.0.0 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from jupyterlab<4.3,>=4.2.0->notebook->jupyter) (2.2.5)
Requirement already satisfied: setuptools>=40.1.0 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from jupyterlab<4.3,>=4.2.0->notebook->jupyter) (69.5.1)
Requirement already satisfied: tomli>=1.2.2 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from jupyterlab<4.3,>=4.2.0->notebook->jupyter) (2.0.1)
Requirement already satisfied: babel>=2.10 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from jupyterlab-server<3,>=2.27.1->notebook->jupyter) (2.16.0)
Requirement already satisfied: json5>=0.9.0 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from jupyterlab-server<3,>=2.27.1->notebook->jupyter) (0.9.25)
Requirement already satisfied: jsonschema>=4.18.0 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from jupyterlab-server<3,>=2.27.1->notebook->jupyter) (4.23.0)
Requirement already satisfied: requests>=2.31 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from jupyterlab-server<3,>=2.27.1->notebook->jupyter) (2.32.3)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from nbformat>=5.7->nbconvert->jupyter) (2.20.0)
Requirement already satisfied: wcwidth in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.2.13)
Requirement already satisfied: soupsieve>1.2 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from beautifulsoup4->nbconvert->jupyter) (2.6)
Requirement already satisfied: executing>=1.2.0 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (2.0.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (2.4.1)
Requirement already satisfied: pure-eval in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (0.2.2)
Requirement already satisfied: idna>=2.8 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (3.8)
Requirement already satisfied: sniffio>=1.1 in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (1.3.1)
Requirement already satisfied: argon2-cffi-bindings in c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook->jupyter) (21.2.0)

WARNING: Ignoring invalid distribution -atplotlib (c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\jazpi\anaconda3\envs\machinelearning\lib\site-packages)

In [47]:
#import sys
#import os

# Agrega el directorio que contiene config.py al path
#sys.path.append('C:/Users/jazpi/Documents/TheBridge_DSPT_ML/PROYECTO_FINAL_ML/03_src')

# Ahora importa config.py como un módulo
#import config

In [48]:
# config.py
import pandas as pd
import numpy as np
import re
import os
import openpyxl
print("config.py se ha ejecutado correctamente.")

config.py se ha ejecutado correctamente.

In [49]:

#file_path = 'C:/Users/jazpi/Documents/TheBridge_DSPT_ML/PROYECTO_FINAL_ML/01_data/02_processed/combined_source_df.csv'
#print("File exists:", os.path.isfile(file_path))

In [50]:
combined_source_df = pd.read_csv(r'C:\Users\jazpi\Documents\TheBridge_DSPT_ML\PROYECTO_FINAL_ML\01_data\02_processed\combined_source_df.csv')

In [51]:
combined_source_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15712 entries, 0 to 15711
Data columns (total 25 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Posición                 15712 non-null  int64
 1   Llegada                  15712 non-null  object
 2   Salida                   15712 non-null  object
 3   Apartamento              15712 non-null  object
 4   Portal de reserva        15712 non-null  object
 5   Creado                   15712 non-null  object
 6   Dirección                0 non-null      float64
 7   Adultos                  13268 non-null  float64
 8   Niños                    2922 non-null   float64
 9   Check-in                 10953 non-null  object
 10  Check-out                10855 non-null  object
 11  Notas                    13440 non-null  object
 12  Precio                   14243 non-null  float64
 13  Detalles de precios      12649 non-null  object
 14  Comisión incluida        12637 non-null  float64
 15  City tax                 0 non-null      float64
 16  Pagado                   15712 non-null  object
 17  Pago por adelantado      4 non-null      float64
 18  Adelanto ya pagado       15712 non-null  object
 19  Número de noches         15712 non-null  int64
 20  Estado                   15712 non-null  object
 21  Nota para colaboradores  9 non-null      object
 22  Huésped_Token            15712 non-null  object
 23  Teléfono_Token           15712 non-null  object
 24  Email_Token              15712 non-null  object
dtypes: float64(7), int64(2), object(16)
memory usage: 3.0+ MB

In [52]:
print(combined_source_df[['Creado', 'Check-in', 'Check-out', 'Llegada', 'Salida']].head())

           Creado Check-in Check-out   Llegada    Salida
0  31.12.22 21:56    16:00     11:00  31.12.22  01.01.23
1  31.12.22 21:56    16:00     11:00  31.12.22  01.01.23
2  31.12.22 21:56    16:00     11:00  31.12.22  01.01.23
3  31.12.22 21:55      NaN       NaN  31.12.22  01.01.23
4  30.12.22 22:03    16:00     11:00  30.12.22  31.12.22

In [53]:
#Identificamos fechas con dtypes Objects y actualizamos a Datetime
combined_source_df['Check-in'] = pd.to_datetime(combined_source_df['Check-in'],format=('%H:%M'))
combined_source_df['Check-out'] = pd.to_datetime(combined_source_df['Check-out'],format=('%H:%M'))
combined_source_df['Creado'] = pd.to_datetime(combined_source_df['Creado'])
combined_source_df['Llegada'] = pd.to_datetime(combined_source_df['Llegada'])
combined_source_df['Salida'] = pd.to_datetime(combined_source_df['Salida'])
combined_source_df.info()

#df['fecha'] = pd.to_datetime(df['fecha'], format='%Y-%m-%d')

C:\Users\jazpi\AppData\Local\Temp\ipykernel_21800\3696615962.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  combined_source_df['Creado'] = pd.to_datetime(combined_source_df['Creado'])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15712 entries, 0 to 15711
Data columns (total 25 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Posición                 15712 non-null  int64
 1   Llegada                  15712 non-null  datetime64[ns]
 2   Salida                   15712 non-null  datetime64[ns]
 3   Apartamento              15712 non-null  object
 4   Portal de reserva        15712 non-null  object
 5   Creado                   15712 non-null  datetime64[ns]
 6   Dirección                0 non-null      float64
 7   Adultos                  13268 non-null  float64
 8   Niños                    2922 non-null   float64
 9   Check-in                 10953 non-null  datetime64[ns]
 10  Check-out                10855 non-null  datetime64[ns]
 11  Notas                    13440 non-null  object
 12  Precio                   14243 non-null  float64
 13  Detalles de precios      12649 non-null  object
 14  Comisión incluida        12637 non-null  float64
 15  City tax                 0 non-null      float64
 16  Pagado                   15712 non-null  object
 17  Pago por adelantado      4 non-null      float64
 18  Adelanto ya pagado       15712 non-null  object
 19  Número de noches         15712 non-null  int64
 20  Estado                   15712 non-null  object
 21  Nota para colaboradores  9 non-null      object
 22  Huésped_Token            15712 non-null  object
 23  Teléfono_Token           15712 non-null  object
 24  Email_Token              15712 non-null  object
dtypes: datetime64[ns](5), float64(7), int64(2), object(11)
memory usage: 3.0+ MB

C:\Users\jazpi\AppData\Local\Temp\ipykernel_21800\3696615962.py:5: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  combined_source_df['Llegada'] = pd.to_datetime(combined_source_df['Llegada'])
C:\Users\jazpi\AppData\Local\Temp\ipykernel_21800\3696615962.py:6: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  combined_source_df['Salida'] = pd.to_datetime(combined_source_df['Salida'])

In [54]:
# Extraer solo la parte de la hora
combined_source_df['Check-in'] = combined_source_df['Check-in'].dt.strftime('%H:%M')
combined_source_df['Check-out'] = combined_source_df['Check-out'].dt.strftime('%H:%M')

![VALORES FALTANTES](VALORES_FALTANTES.png)


### Vemos que las variables *Dirección*, *City tax*, *Pago por adelantado* y *Nota de Colaboradores* no tienen ninguna observación informada-
### VAMOS A ELIMINARLAS

In [55]:

# Eliminar la columna 'Dirección'
combined_source_df_cleaned = combined_source_df.drop(['Dirección', 'City tax', 'Pago por adelantado','Nota para colaboradores'], axis=1)

# Mostrar el DataFrame resultante
print(combined_source_df_cleaned)

       Posición    Llegada     Salida      Apartamento  \
0      32518147 2022-12-31 2023-01-01        HD OLIVIA
1      32518144 2022-12-31 2023-01-01         HD FIDEL
2      32518120 2022-12-31 2023-01-01     HD ALEJANDRA
3      32518117 2022-12-31 2023-01-01     H BMA LISBOA
4      32489530 2022-12-30 2022-12-31        HD OLIVIA
...         ...        ...        ...              ...
15707  48020365 2024-06-17 2024-06-21       H - BUA 3P
15708  46670629 2024-11-02 2024-12-02  H BMA AMSTERDAM
15709  46642321 2024-12-01 2024-01-14     H BMA BERLIN
15710  46642318 2024-12-01 2024-01-14  H BMA AMSTERDAM
15711  45005552 2024-08-01 2024-10-01      HG0 MUGARRA

             Portal de reserva              Creado  Adultos  Niños Check-in  \
0      Cerrar fechas (bloqueo) 2022-12-31 21:56:00      NaN    NaN    16:00
1      Cerrar fechas (bloqueo) 2022-12-31 21:56:00      NaN    NaN    16:00
2      Cerrar fechas (bloqueo) 2022-12-31 21:56:00      NaN    NaN    16:00
3      Cerrar fechas (bloqueo) 2022-12-31 21:55:00      NaN    NaN      NaN
4      Cerrar fechas (bloqueo) 2022-12-30 22:03:00      NaN    NaN    16:00
...                        ...                 ...      ...    ...      ...
15707          Reserva directa 2023-10-23 12:17:00      1.0    NaN    16:00
15708              Booking.com 2023-09-26 14:51:00      7.0    NaN    16:00
15709              Booking.com 2023-09-25 23:26:00      6.0    NaN    16:00
15710              Booking.com 2023-09-25 23:26:00      5.0    NaN    16:00
15711                   Airbnb 2023-08-26 11:09:00      7.0    NaN    16:00

      Check-out  ...  Precio  \
0         11:00  ...     NaN
1         11:00  ...     NaN
2         11:00  ...     NaN
3           NaN  ...     NaN
4         11:00  ...     NaN
...         ...  ...     ...
15707     11:00  ...  520.00
15708     11:00  ...  159.25
15709     11:00  ...  521.60
15710     11:00  ...  671.80
15711     11:00  ...  261.80

                                     Detalles de precios Comisión incluida  \
0                                                    NaN               NaN
1                                                    NaN               NaN
2                                                    NaN               NaN
3                                                    NaN               NaN
4                                                    NaN               NaN
...                                                  ...               ...
15707                                                NaN               NaN
15708                                    TVA - EUR 14.48             23.89
15709                                    TVA - EUR 47.42             78.24
15710                                    TVA - EUR 61.07            100.77
15711  Cancellation Host Fee - EUR 35.7\nCancellation...             35.70

       Pagado Adelanto ya pagado Número de noches     Estado  \
0          No                 No                1  Reservado
1          No                 No                1  Reservado
2          No                 No                1  Reservado
3          No                 No                1  Reservado
4          No                 No                1  Reservado
...       ...                ...              ...        ...
15707      No                 No                4  Reservado
15708      Sí                 No                1  Cancelado
15709      Sí                 No                2  Cancelado
15710      Sí                 No                2  Cancelado
15711      Sí                 No                2  Reservado

                              Huésped_Token  \
0      71a01995-5e56-4d2e-a62e-d29ffa113727
1      e9690362-ef85-46b9-b57b-9c103a393132
2      98b093ab-4af2-4766-a4ac-9e5128d85f39
3      3681b31b-22c1-4feb-8082-ed93df68dc60
4      7158087e-ce04-4eca-adcc-007c2800b8d3
...                                     ...
15707  ae5ac6f3-f5fd-4c9f-a49b-878dd6766f68
15708  283cc4b5-618b-42f9-89b7-aa4631d43598
15709  8b7ca7d0-fd9e-48da-ba2f-89a34b4cf443
15710  bac8c862-bc62-4833-a830-6c575c1db844
15711  6dcfc64f-e2d4-4bae-a67c-e0fdbf68fe1a

                             Teléfono_Token  \
0      9987c264-6c50-4def-b755-3ed5c857069c
1      51c5691e-4ee2-4179-b081-3edf909bceaa
2      6d67292c-3638-40e9-bd7e-5dde788d576f
3      da19f878-7f70-4d86-a6ed-6ec9a23bc0c7
4      22a14603-058c-4eec-8dcd-128e3dbc0e39
...                                     ...
15707  c7d507bc-de2c-4311-9771-ebe8e1975a54
15708  56eca6d3-120b-438c-8196-f6417e4a963c
15709  00fd1333-deb8-4200-8855-761061f02719
15710  125ce295-efb3-4282-aab7-6bc5fe150685
15711  310d2c3c-fc30-45c6-bdba-cd327e55caef

                                Email_Token
0      355ee9b8-0b11-40ad-8483-326f5b7666d1
1      da00d123-4de1-4058-9d9e-a788812c3c9e
2      15724081-c7ec-4d11-8fb3-12ae2acaa1c9
3      8c61aa5f-2010-4a92-bbf2-13e5ccd612e0
4      dc94416d-1785-422d-8925-d3ac597669e2
...                                     ...
15707  43094cc6-d7e8-44a1-9718-24ec2e6cd178
15708  e2b227d4-3c0b-45a2-983b-e9c4ef832c55
15709  c9df92c9-1cf7-4b3e-962e-a21082ce6852
15710  a3bdfc2f-23a1-43c7-9a00-1f4f6f56dce1
15711  381c7540-d065-4490-bb9d-9bd29a1f425e

[15712 rows x 21 columns]

In [56]:
condicion = combined_source_df_cleaned['Portal de reserva'] == 'Cerrar fechas (bloqueo)'
combined_source_df_cleaned[condicion]

,Posición,Llegada,Salida,Apartamento,Portal de reserva,Creado,Adultos,Niños,Check-in,Check-out,...,Precio,Detalles de precios,Comisión incluida,Pagado,Adelanto ya pagado,Número de noches,Estado,Huésped_Token,Teléfono_Token,Email_Token
0,32518147,2022-12-31,2023-01-01,HD OLIVIA,Cerrar fechas (bloqueo),2022-12-31 21:56:00,NaN,NaN,16:00,11:00,...,NaN,NaN,NaN,No,No,1,Reservado,71a01995-5e56-4d2e-a62e-d29ffa113727,9987c264-6c50-4def-b755-3ed5c857069c,355ee9b8-0b11-40ad-8483-326f5b7666d1
1,32518144,2022-12-31,2023-01-01,HD FIDEL,Cerrar fechas (bloqueo),2022-12-31 21:56:00,NaN,NaN,16:00,11:00,...,NaN,NaN,NaN,No,No,1,Reservado,e9690362-ef85-46b9-b57b-9c103a393132,51c5691e-4ee2-4179-b081-3edf909bceaa,da00d123-4de1-4058-9d9e-a788812c3c9e
2,32518120,2022-12-31,2023-01-01,HD ALEJANDRA,Cerrar fechas (bloqueo),2022-12-31 21:56:00,NaN,NaN,16:00,11:00,...,NaN,NaN,NaN,No,No,1,Reservado,98b093ab-4af2-4766-a4ac-9e5128d85f39,6d67292c-3638-40e9-bd7e-5dde788d576f,15724081-c7ec-4d11-8fb3-12ae2acaa1c9
3,32518117,2022-12-31,2023-01-01,H BMA LISBOA,Cerrar fechas (bloqueo),2022-12-31 21:55:00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,No,No,1,Reservado,3681b31b-22c1-4feb-8082-ed93df68dc60,da19f878-7f70-4d86-a6ed-6ec9a23bc0c7,8c61aa5f-2010-4a92-bbf2-13e5ccd612e0
4,32489530,2022-12-30,2022-12-31,HD OLIVIA,Cerrar fechas (bloqueo),2022-12-30 22:03:00,NaN,NaN,16:00,11:00,...,NaN,NaN,NaN,No,No,1,Reservado,7158087e-ce04-4eca-adcc-007c2800b8d3,22a14603-058c-4eec-8dcd-128e3dbc0e39,dc94416d-1785-422d-8925-d3ac597669e2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15495,51533765,2024-09-01,2024-11-01,HD BRUNO,Cerrar fechas (bloqueo),2024-06-01 13:43:00,NaN,NaN,16:00,11:00,...,NaN,NaN,NaN,No,No,2,Cancelado,43dae62a-3c97-40c6-97e1-9401253b5ea4,041db86a-666e-4912-97a0-575ee6c7b88c,c30edfc7-8da6-416c-88b8-feb2c753cf17
15496,51533711,2024-07-01,2024-09-01,HD ALEJANDRA,Cerrar fechas (bloqueo),2024-06-01 13:43:00,NaN,NaN,16:00,11:00,...,NaN,NaN,NaN,No,No,2,Cancelado,2e2793d1-0cc7-4c6f-968d-910ae60e7428,cd58a82f-b0e1-49b5-b92b-e0650fb2418f,d6409714-6d50-4266-9584-628598cad9a5
15531,51405551,2024-12-01,2024-01-13,H - BUA 3P,Cerrar fechas (bloqueo),2024-04-01 11:23:00,NaN,NaN,16:00,11:00,...,NaN,NaN,NaN,No,No,1,Cancelado,252d7cf2-ec5c-4cf6-a630-bba701bb1924,4270393d-8282-4a89-818d-bcf20b242acc,c3f9a0ee-5acf-493a-be2d-07132f38a8a5
15532,51405221,2024-11-01,2024-12-01,H - BUA 3P,Cerrar fechas (bloqueo),2024-04-01 11:19:00,NaN,NaN,16:00,11:00,...,NaN,NaN,NaN,No,No,1,Reservado,c123d9cd-d3eb-46c9-9093-53fdc186a424,cc60ec29-5a6d-485f-a64b-796807516d29,9cb45e66-e889-43ef-ba15-b1ef3fb521e3
15572,51238430,2024-01-01,2024-02-01,H BMA OSLO,Cerrar fechas (bloqueo),2024-01-01 14:21:00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,No,No,1,Reservado,f07293ee-ae47-4d44-80d4-34672d080902,823ec494-5ba0-435b-a67e-6600c053b727,cf1b32a8-b0e8-4bd3-bd11-d203f2cc0402

### En este caso, Vemos que las variables *Portal de reserva*está fatal informada cuando el origen de la reserva es un bloqueo interno de esos apartamentos.
### VAMOS A ELIMINARLAS ESAS FILAS

In [57]:
# Eliminar las filas donde 'Portal de reservas' es 'Cerrar fechas (bloqueo)'
condicion2 = combined_source_df_cleaned['Portal de reserva'] != 'Cerrar fechas (bloqueo)'
combined_source_df_cleaned[condicion2]

,Posición,Llegada,Salida,Apartamento,Portal de reserva,Creado,Adultos,Niños,Check-in,Check-out,...,Precio,Detalles de precios,Comisión incluida,Pagado,Adelanto ya pagado,Número de noches,Estado,Huésped_Token,Teléfono_Token,Email_Token
13,32474470,2022-12-30,2023-01-01,H BMA MONACO,Booking.com,2022-12-30 15:16:00,1.0,1.0,NaN,NaN,...,234.90,TVA - EUR 21.35,35.23,Sí,No,2,Reservado,165b0a32-f0de-472f-91b0-f4db1a5de1e9,ac05586d-fcf0-48c9-951a-a543d2b662d9,9f635b58-7a19-4339-95bf-43a633fb37c0
15,32470780,2022-12-30,2022-12-31,H BMA HELSINKI,Booking.com,2022-12-30 13:38:00,2.0,NaN,NaN,NaN,...,95.00,TVA - EUR 8.64,14.25,Sí,No,1,Reservado,f37086d0-e2ed-4564-af38-1a5c9babff7f,09f22c11-951f-4154-a498-457caca71a3e,0407639f-425f-4566-8ef3-5958633ba344
16,32469028,2022-12-31,2023-04-01,H BMA GARAJE,Reserva directa,2022-12-30 12:50:00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,No,No,4,Reservado,c329d52c-fe36-4bb7-85e6-0b02bf96d77f,5a8e7559-70e4-4c45-8f5e-bc42443d285f,197e6741-3144-47fe-81eb-c0569b0a0861
17,32407618,2022-12-31,2023-01-01,H BMA DUBLIN,Booking.com,2022-12-28 20:36:00,4.0,NaN,NaN,NaN,...,245.00,TVA - EUR 22.27,36.75,Sí,No,1,Reservado,48fb4129-e9c0-4401-aa99-fbbbcf2903b2,c697a2e4-6368-4a79-9616-3780ec063f6b,777a9013-c353-4b3c-895b-ac80e028c801
18,32401555,2022-12-28,2022-12-30,HD-GARAJE 5,Reserva directa,2022-12-28 18:20:00,NaN,NaN,NaN,NaN,...,40.00,NaN,NaN,No,No,2,Reservado,f4289cb9-3b56-40f4-b80f-d4c04432ebcb,9a35c9a1-ed21-4b64-a5fc-550221e3c822,558387d5-bf34-4d7c-90a4-45fc11a2918a
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15707,48020365,2024-06-17,2024-06-21,H - BUA 3P,Reserva directa,2023-10-23 12:17:00,1.0,NaN,16:00,11:00,...,520.00,NaN,NaN,No,No,4,Reservado,ae5ac6f3-f5fd-4c9f-a49b-878dd6766f68,c7d507bc-de2c-4311-9771-ebe8e1975a54,43094cc6-d7e8-44a1-9718-24ec2e6cd178
15708,46670629,2024-11-02,2024-12-02,H BMA AMSTERDAM,Booking.com,2023-09-26 14:51:00,7.0,NaN,16:00,11:00,...,159.25,TVA - EUR 14.48,23.89,Sí,No,1,Cancelado,283cc4b5-618b-42f9-89b7-aa4631d43598,56eca6d3-120b-438c-8196-f6417e4a963c,e2b227d4-3c0b-45a2-983b-e9c4ef832c55
15709,46642321,2024-12-01,2024-01-14,H BMA BERLIN,Booking.com,2023-09-25 23:26:00,6.0,NaN,16:00,11:00,...,521.60,TVA - EUR 47.42,78.24,Sí,No,2,Cancelado,8b7ca7d0-fd9e-48da-ba2f-89a34b4cf443,00fd1333-deb8-4200-8855-761061f02719,c9df92c9-1cf7-4b3e-962e-a21082ce6852
15710,46642318,2024-12-01,2024-01-14,H BMA AMSTERDAM,Booking.com,2023-09-25 23:26:00,5.0,NaN,16:00,11:00,...,671.80,TVA - EUR 61.07,100.77,Sí,No,2,Cancelado,bac8c862-bc62-4833-a830-6c575c1db844,125ce295-efb3-4282-aab7-6bc5fe150685,a3bdfc2f-23a1-43c7-9a00-1f4f6f56dce1
15711,45005552,2024-08-01,2024-10-01,HG0 MUGARRA,Airbnb,2023-08-26 11:09:00,7.0,NaN,16:00,11:00,...,261.80,Cancellation Host Fee - EUR 35.7\nCancellation...,35.70,Sí,No,2,Reservado,6dcfc64f-e2d4-4bae-a67c-e0fdbf68fe1a,310d2c3c-fc30-45c6-bdba-cd327e55caef,381c7540-d065-4490-bb9d-9bd29a1f425e

In [58]:
combined_source_df_cleaned = combined_source_df_cleaned[condicion2] 
combined_source_df_cleaned

,Posición,Llegada,Salida,Apartamento,Portal de reserva,Creado,Adultos,Niños,Check-in,Check-out,...,Precio,Detalles de precios,Comisión incluida,Pagado,Adelanto ya pagado,Número de noches,Estado,Huésped_Token,Teléfono_Token,Email_Token
13,32474470,2022-12-30,2023-01-01,H BMA MONACO,Booking.com,2022-12-30 15:16:00,1.0,1.0,NaN,NaN,...,234.90,TVA - EUR 21.35,35.23,Sí,No,2,Reservado,165b0a32-f0de-472f-91b0-f4db1a5de1e9,ac05586d-fcf0-48c9-951a-a543d2b662d9,9f635b58-7a19-4339-95bf-43a633fb37c0
15,32470780,2022-12-30,2022-12-31,H BMA HELSINKI,Booking.com,2022-12-30 13:38:00,2.0,NaN,NaN,NaN,...,95.00,TVA - EUR 8.64,14.25,Sí,No,1,Reservado,f37086d0-e2ed-4564-af38-1a5c9babff7f,09f22c11-951f-4154-a498-457caca71a3e,0407639f-425f-4566-8ef3-5958633ba344
16,32469028,2022-12-31,2023-04-01,H BMA GARAJE,Reserva directa,2022-12-30 12:50:00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,No,No,4,Reservado,c329d52c-fe36-4bb7-85e6-0b02bf96d77f,5a8e7559-70e4-4c45-8f5e-bc42443d285f,197e6741-3144-47fe-81eb-c0569b0a0861
17,32407618,2022-12-31,2023-01-01,H BMA DUBLIN,Booking.com,2022-12-28 20:36:00,4.0,NaN,NaN,NaN,...,245.00,TVA - EUR 22.27,36.75,Sí,No,1,Reservado,48fb4129-e9c0-4401-aa99-fbbbcf2903b2,c697a2e4-6368-4a79-9616-3780ec063f6b,777a9013-c353-4b3c-895b-ac80e028c801
18,32401555,2022-12-28,2022-12-30,HD-GARAJE 5,Reserva directa,2022-12-28 18:20:00,NaN,NaN,NaN,NaN,...,40.00,NaN,NaN,No,No,2,Reservado,f4289cb9-3b56-40f4-b80f-d4c04432ebcb,9a35c9a1-ed21-4b64-a5fc-550221e3c822,558387d5-bf34-4d7c-90a4-45fc11a2918a
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15707,48020365,2024-06-17,2024-06-21,H - BUA 3P,Reserva directa,2023-10-23 12:17:00,1.0,NaN,16:00,11:00,...,520.00,NaN,NaN,No,No,4,Reservado,ae5ac6f3-f5fd-4c9f-a49b-878dd6766f68,c7d507bc-de2c-4311-9771-ebe8e1975a54,43094cc6-d7e8-44a1-9718-24ec2e6cd178
15708,46670629,2024-11-02,2024-12-02,H BMA AMSTERDAM,Booking.com,2023-09-26 14:51:00,7.0,NaN,16:00,11:00,...,159.25,TVA - EUR 14.48,23.89,Sí,No,1,Cancelado,283cc4b5-618b-42f9-89b7-aa4631d43598,56eca6d3-120b-438c-8196-f6417e4a963c,e2b227d4-3c0b-45a2-983b-e9c4ef832c55
15709,46642321,2024-12-01,2024-01-14,H BMA BERLIN,Booking.com,2023-09-25 23:26:00,6.0,NaN,16:00,11:00,...,521.60,TVA - EUR 47.42,78.24,Sí,No,2,Cancelado,8b7ca7d0-fd9e-48da-ba2f-89a34b4cf443,00fd1333-deb8-4200-8855-761061f02719,c9df92c9-1cf7-4b3e-962e-a21082ce6852
15710,46642318,2024-12-01,2024-01-14,H BMA AMSTERDAM,Booking.com,2023-09-25 23:26:00,5.0,NaN,16:00,11:00,...,671.80,TVA - EUR 61.07,100.77,Sí,No,2,Cancelado,bac8c862-bc62-4833-a830-6c575c1db844,125ce295-efb3-4282-aab7-6bc5fe150685,a3bdfc2f-23a1-43c7-9a00-1f4f6f56dce1
15711,45005552,2024-08-01,2024-10-01,HG0 MUGARRA,Airbnb,2023-08-26 11:09:00,7.0,NaN,16:00,11:00,...,261.80,Cancellation Host Fee - EUR 35.7\nCancellation...,35.70,Sí,No,2,Reservado,6dcfc64f-e2d4-4bae-a67c-e0fdbf68fe1a,310d2c3c-fc30-45c6-bdba-cd327e55caef,381c7540-d065-4490-bb9d-9bd29a1f425e

In [59]:
combined_source_df_cleaned['Portal de reserva'].unique()

array(['Booking.com', 'Reserva directa', 'Airbnb', 'Página web'],
      dtype=object)

In [60]:
combined_source_df = pd.DataFrame(combined_source_df)

condicion3 = combined_source_df_cleaned['Comisión incluida'].isnull()
combined_source_df_cleaned.loc[condicion3, 'Comisión incluida'] = 0

In [61]:

# Mostrar el DataFrame actualizado
print("\nDataFrame después de ajustar la Comisión incluida:")
print(combined_source_df_cleaned)

DataFrame después de ajustar la Comisión incluida:
       Posición    Llegada     Salida      Apartamento Portal de reserva  \
13     32474470 2022-12-30 2023-01-01     H BMA MONACO       Booking.com
15     32470780 2022-12-30 2022-12-31   H BMA HELSINKI       Booking.com
16     32469028 2022-12-31 2023-04-01     H BMA GARAJE   Reserva directa
17     32407618 2022-12-31 2023-01-01     H BMA DUBLIN       Booking.com
18     32401555 2022-12-28 2022-12-30      HD-GARAJE 5   Reserva directa
...         ...        ...        ...              ...               ...
15707  48020365 2024-06-17 2024-06-21       H - BUA 3P   Reserva directa
15708  46670629 2024-11-02 2024-12-02  H BMA AMSTERDAM       Booking.com
15709  46642321 2024-12-01 2024-01-14     H BMA BERLIN       Booking.com
15710  46642318 2024-12-01 2024-01-14  H BMA AMSTERDAM       Booking.com
15711  45005552 2024-08-01 2024-10-01      HG0 MUGARRA            Airbnb

                   Creado  Adultos  Niños Check-in Check-out  ...  Precio  \
13    2022-12-30 15:16:00      1.0    1.0      NaN       NaN  ...  234.90
15    2022-12-30 13:38:00      2.0    NaN      NaN       NaN  ...   95.00
16    2022-12-30 12:50:00      NaN    NaN      NaN       NaN  ...     NaN
17    2022-12-28 20:36:00      4.0    NaN      NaN       NaN  ...  245.00
18    2022-12-28 18:20:00      NaN    NaN      NaN       NaN  ...   40.00
...                   ...      ...    ...      ...       ...  ...     ...
15707 2023-10-23 12:17:00      1.0    NaN    16:00     11:00  ...  520.00
15708 2023-09-26 14:51:00      7.0    NaN    16:00     11:00  ...  159.25
15709 2023-09-25 23:26:00      6.0    NaN    16:00     11:00  ...  521.60
15710 2023-09-25 23:26:00      5.0    NaN    16:00     11:00  ...  671.80
15711 2023-08-26 11:09:00      7.0    NaN    16:00     11:00  ...  261.80

                                     Detalles de precios Comisión incluida  \
13                                       TVA - EUR 21.35             35.23
15                                        TVA - EUR 8.64             14.25
16                                                   NaN              0.00
17                                       TVA - EUR 22.27             36.75
18                                                   NaN              0.00
...                                                  ...               ...
15707                                                NaN              0.00
15708                                    TVA - EUR 14.48             23.89
15709                                    TVA - EUR 47.42             78.24
15710                                    TVA - EUR 61.07            100.77
15711  Cancellation Host Fee - EUR 35.7\nCancellation...             35.70

       Pagado Adelanto ya pagado Número de noches     Estado  \
13         Sí                 No                2  Reservado
15         Sí                 No                1  Reservado
16         No                 No                4  Reservado
17         Sí                 No                1  Reservado
18         No                 No                2  Reservado
...       ...                ...              ...        ...
15707      No                 No                4  Reservado
15708      Sí                 No                1  Cancelado
15709      Sí                 No                2  Cancelado
15710      Sí                 No                2  Cancelado
15711      Sí                 No                2  Reservado

                              Huésped_Token  \
13     165b0a32-f0de-472f-91b0-f4db1a5de1e9
15     f37086d0-e2ed-4564-af38-1a5c9babff7f
16     c329d52c-fe36-4bb7-85e6-0b02bf96d77f
17     48fb4129-e9c0-4401-aa99-fbbbcf2903b2
18     f4289cb9-3b56-40f4-b80f-d4c04432ebcb
...                                     ...
15707  ae5ac6f3-f5fd-4c9f-a49b-878dd6766f68
15708  283cc4b5-618b-42f9-89b7-aa4631d43598
15709  8b7ca7d0-fd9e-48da-ba2f-89a34b4cf443
15710  bac8c862-bc62-4833-a830-6c575c1db844
15711  6dcfc64f-e2d4-4bae-a67c-e0fdbf68fe1a

                             Teléfono_Token  \
13     ac05586d-fcf0-48c9-951a-a543d2b662d9
15     09f22c11-951f-4154-a498-457caca71a3e
16     5a8e7559-70e4-4c45-8f5e-bc42443d285f
17     c697a2e4-6368-4a79-9616-3780ec063f6b
18     9a35c9a1-ed21-4b64-a5fc-550221e3c822
...                                     ...
15707  c7d507bc-de2c-4311-9771-ebe8e1975a54
15708  56eca6d3-120b-438c-8196-f6417e4a963c
15709  00fd1333-deb8-4200-8855-761061f02719
15710  125ce295-efb3-4282-aab7-6bc5fe150685
15711  310d2c3c-fc30-45c6-bdba-cd327e55caef

                                Email_Token
13     9f635b58-7a19-4339-95bf-43a633fb37c0
15     0407639f-425f-4566-8ef3-5958633ba344
16     197e6741-3144-47fe-81eb-c0569b0a0861
17     777a9013-c353-4b3c-895b-ac80e028c801
18     558387d5-bf34-4d7c-90a4-45fc11a2918a
...                                     ...
15707  43094cc6-d7e8-44a1-9718-24ec2e6cd178
15708  e2b227d4-3c0b-45a2-983b-e9c4ef832c55
15709  c9df92c9-1cf7-4b3e-962e-a21082ce6852
15710  a3bdfc2f-23a1-43c7-9a00-1f4f6f56dce1
15711  381c7540-d065-4490-bb9d-9bd29a1f425e

[14386 rows x 21 columns]

In [62]:
combined_source_df_cleaned['Comisión incluida'].isna()

13       False
15       False
16       False
17       False
18       False
         ...
15707    False
15708    False
15709    False
15710    False
15711    False
Name: Comisión incluida, Length: 14386, dtype: bool

In [63]:
combined_source_df_cleaned['Comisión incluida'].info()

<class 'pandas.core.series.Series'>
Index: 14386 entries, 13 to 15711
Series name: Comisión incluida
Non-Null Count  Dtype
--------------  -----
14386 non-null  float64
dtypes: float64(1)
memory usage: 224.8 KB

In [64]:
combined_source_df_cleaned

,Posición,Llegada,Salida,Apartamento,Portal de reserva,Creado,Adultos,Niños,Check-in,Check-out,...,Precio,Detalles de precios,Comisión incluida,Pagado,Adelanto ya pagado,Número de noches,Estado,Huésped_Token,Teléfono_Token,Email_Token
13,32474470,2022-12-30,2023-01-01,H BMA MONACO,Booking.com,2022-12-30 15:16:00,1.0,1.0,NaN,NaN,...,234.90,TVA - EUR 21.35,35.23,Sí,No,2,Reservado,165b0a32-f0de-472f-91b0-f4db1a5de1e9,ac05586d-fcf0-48c9-951a-a543d2b662d9,9f635b58-7a19-4339-95bf-43a633fb37c0
15,32470780,2022-12-30,2022-12-31,H BMA HELSINKI,Booking.com,2022-12-30 13:38:00,2.0,NaN,NaN,NaN,...,95.00,TVA - EUR 8.64,14.25,Sí,No,1,Reservado,f37086d0-e2ed-4564-af38-1a5c9babff7f,09f22c11-951f-4154-a498-457caca71a3e,0407639f-425f-4566-8ef3-5958633ba344
16,32469028,2022-12-31,2023-04-01,H BMA GARAJE,Reserva directa,2022-12-30 12:50:00,NaN,NaN,NaN,NaN,...,NaN,NaN,0.00,No,No,4,Reservado,c329d52c-fe36-4bb7-85e6-0b02bf96d77f,5a8e7559-70e4-4c45-8f5e-bc42443d285f,197e6741-3144-47fe-81eb-c0569b0a0861
17,32407618,2022-12-31,2023-01-01,H BMA DUBLIN,Booking.com,2022-12-28 20:36:00,4.0,NaN,NaN,NaN,...,245.00,TVA - EUR 22.27,36.75,Sí,No,1,Reservado,48fb4129-e9c0-4401-aa99-fbbbcf2903b2,c697a2e4-6368-4a79-9616-3780ec063f6b,777a9013-c353-4b3c-895b-ac80e028c801
18,32401555,2022-12-28,2022-12-30,HD-GARAJE 5,Reserva directa,2022-12-28 18:20:00,NaN,NaN,NaN,NaN,...,40.00,NaN,0.00,No,No,2,Reservado,f4289cb9-3b56-40f4-b80f-d4c04432ebcb,9a35c9a1-ed21-4b64-a5fc-550221e3c822,558387d5-bf34-4d7c-90a4-45fc11a2918a
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15707,48020365,2024-06-17,2024-06-21,H - BUA 3P,Reserva directa,2023-10-23 12:17:00,1.0,NaN,16:00,11:00,...,520.00,NaN,0.00,No,No,4,Reservado,ae5ac6f3-f5fd-4c9f-a49b-878dd6766f68,c7d507bc-de2c-4311-9771-ebe8e1975a54,43094cc6-d7e8-44a1-9718-24ec2e6cd178
15708,46670629,2024-11-02,2024-12-02,H BMA AMSTERDAM,Booking.com,2023-09-26 14:51:00,7.0,NaN,16:00,11:00,...,159.25,TVA - EUR 14.48,23.89,Sí,No,1,Cancelado,283cc4b5-618b-42f9-89b7-aa4631d43598,56eca6d3-120b-438c-8196-f6417e4a963c,e2b227d4-3c0b-45a2-983b-e9c4ef832c55
15709,46642321,2024-12-01,2024-01-14,H BMA BERLIN,Booking.com,2023-09-25 23:26:00,6.0,NaN,16:00,11:00,...,521.60,TVA - EUR 47.42,78.24,Sí,No,2,Cancelado,8b7ca7d0-fd9e-48da-ba2f-89a34b4cf443,00fd1333-deb8-4200-8855-761061f02719,c9df92c9-1cf7-4b3e-962e-a21082ce6852
15710,46642318,2024-12-01,2024-01-14,H BMA AMSTERDAM,Booking.com,2023-09-25 23:26:00,5.0,NaN,16:00,11:00,...,671.80,TVA - EUR 61.07,100.77,Sí,No,2,Cancelado,bac8c862-bc62-4833-a830-6c575c1db844,125ce295-efb3-4282-aab7-6bc5fe150685,a3bdfc2f-23a1-43c7-9a00-1f4f6f56dce1
15711,45005552,2024-08-01,2024-10-01,HG0 MUGARRA,Airbnb,2023-08-26 11:09:00,7.0,NaN,16:00,11:00,...,261.80,Cancellation Host Fee - EUR 35.7\nCancellation...,35.70,Sí,No,2,Reservado,6dcfc64f-e2d4-4bae-a67c-e0fdbf68fe1a,310d2c3c-fc30-45c6-bdba-cd327e55caef,381c7540-d065-4490-bb9d-9bd29a1f425e

In [65]:
combined_source_df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14386 entries, 13 to 15711
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Posición             14386 non-null  int64
 1   Llegada              14386 non-null  datetime64[ns]
 2   Salida               14386 non-null  datetime64[ns]
 3   Apartamento          14386 non-null  object
 4   Portal de reserva    14386 non-null  object
 5   Creado               14386 non-null  datetime64[ns]
 6   Adultos              13267 non-null  float64
 7   Niños                2922 non-null   float64
 8   Check-in             10065 non-null  object
 9   Check-out            9967 non-null   object
 10  Notas                13423 non-null  object
 11  Precio               14241 non-null  float64
 12  Detalles de precios  12649 non-null  object
 13  Comisión incluida    14386 non-null  float64
 14  Pagado               14386 non-null  object
 15  Adelanto ya pagado   14386 non-null  object
 16  Número de noches     14386 non-null  int64
 17  Estado               14386 non-null  object
 18  Huésped_Token        14386 non-null  object
 19  Teléfono_Token       14386 non-null  object
 20  Email_Token          14386 non-null  object
dtypes: datetime64[ns](3), float64(4), int64(2), object(12)
memory usage: 2.4+ MB

In [66]:
combined_source_df_cleaned.describe()

,Posición,Llegada,Salida,Creado,Adultos,Niños,Precio,Comisión incluida,Número de noches
count,1.438600e+04,14386,14386,14386,13267.000000,2922.000000,14241.000000,14386.000000,14386.000000
mean,4.270972e+07,2023-07-05 08:10:40.622828032,2023-07-07 08:12:46.745446912,2023-06-27 03:10:42.328652800,2.644456,1.761807,230.438834,30.834147,1.828792
min,1.539014e+07,2021-12-19 00:00:00,2022-01-02 00:00:00,2021-02-12 11:22:00,1.000000,1.000000,1.150000,0.000000,1.000000
25%,2.997241e+07,2022-11-06 00:00:00,2022-11-07 00:00:00,2022-10-27 11:09:30,2.000000,1.000000,81.900000,10.650000,1.000000
50%,4.228362e+07,2023-07-20 00:00:00,2023-07-24 00:00:00,2023-07-05 19:36:00,2.000000,2.000000,148.000000,20.250000,1.000000
75%,5.427418e+07,2024-03-14 00:00:00,2024-03-17 00:00:00,2024-02-26 21:46:30,3.000000,2.000000,272.000000,38.240000,2.000000
max,6.985467e+07,2024-12-11 00:00:00,2024-12-08 00:00:00,2024-12-08 23:16:00,8.000000,7.000000,7847.600000,867.750000,91.000000
std,1.447137e+07,NaN,NaN,NaN,1.370796,0.719993,292.345751,37.945631,2.098335

### En este caso, Vemos que las variables *Notas* está informada con muca información entre ellas 'Numero de reserva', 'Mensaje de Cliente', 'Mensaje de Booking', si es Genius o no.
### VAMOS A EXTRAER ESA informacion a nuevas columnas

In [67]:
print(combined_source_df_cleaned['Notas'].head(1000))

13      Número de reserva: 3509184945\nMensaje del hué...
15      Número de reserva: 3677697588\nMensaje del hué...
16                                                    NaN
17      Número de reserva: 2331981900\nMensaje del hué...
18                                           Trjeta 28.12
                              ...
1210    Número de reserva: 3768511260\nMensaje del hué...
1211    Número de reserva: HMNDEZMPEH\nIdioma del hués...
1212    Número de reserva: HMQX24ANFK\nIdioma del hués...
1213    Número de reserva: 2894245314\nMensaje del hué...
1214    Número de reserva: 3040511008\nMensaje del hué...
Name: Notas, Length: 1000, dtype: object

In [68]:
# Extraer el número después de 'Mensaje del huésped:'
combined_source_df_cleaned['Numero_Reserva'] = combined_source_df_cleaned['Notas'].str.extract(r'Número de reserva: (\d+)')
# Extraer el texto después de 'Mensaje del huésped:'
combined_source_df_cleaned['Mensaje_Huesped'] = combined_source_df_cleaned['Notas'].str.extract(r'Mensaje del huésped:\s*(.*)\s*BOOKING NOTE:')
# Extraer el texto después de 'BOOKING NOTE:'
combined_source_df_cleaned['BOOKING_NOTE'] = combined_source_df_cleaned['Notas'].str.extract(r'BOOKING NOTE\s*:\s*(.*)')

combined_source_df_cleaned[['BOOKING_NOTE', 'Mensaje_Huesped']] = combined_source_df_cleaned['BOOKING_NOTE'].str.extract(r'(Payment charge is EUR \d+\.\d+)\s*(.*)')

# Crear la nueva columna 'GENIUS' que sea True si 'booker_is_genius' está en 'Texto'
combined_source_df_cleaned['GENIUS'] = combined_source_df_cleaned['Notas'].str.contains('booker_is_genius', case=False, na=False)

# Mostrar el DataFrame modificado
print("\nDataFrame modificado:")
print(combined_source_df_cleaned[['Numero_Reserva','BOOKING_NOTE','Mensaje_Huesped','GENIUS']])

combined_source_df_cleaned.info()

DataFrame modificado:
      Numero_Reserva                   BOOKING_NOTE Mensaje_Huesped  GENIUS
13        3509184945   Payment charge is EUR 2.5839                    True
15        3677697588    Payment charge is EUR 1.045                    True
16               NaN                            NaN             NaN   False
17        2331981900    Payment charge is EUR 2.695                    True
18               NaN                            NaN             NaN   False
...              ...                            ...             ...     ...
15707            NaN                            NaN             NaN   False
15708     4232587055  Payment charge is EUR 1.75175                    True
15709     4237415932  Payment charge is EUR 13.1274                    True
15710     4237415932  Payment charge is EUR 13.1274                    True
15711            NaN                            NaN             NaN   False

[14386 rows x 4 columns]
<class 'pandas.core.frame.DataFrame'>
Index: 14386 entries, 13 to 15711
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Posición             14386 non-null  int64
 1   Llegada              14386 non-null  datetime64[ns]
 2   Salida               14386 non-null  datetime64[ns]
 3   Apartamento          14386 non-null  object
 4   Portal de reserva    14386 non-null  object
 5   Creado               14386 non-null  datetime64[ns]
 6   Adultos              13267 non-null  float64
 7   Niños                2922 non-null   float64
 8   Check-in             10065 non-null  object
 9   Check-out            9967 non-null   object
 10  Notas                13423 non-null  object
 11  Precio               14241 non-null  float64
 12  Detalles de precios  12649 non-null  object
 13  Comisión incluida    14386 non-null  float64
 14  Pagado               14386 non-null  object
 15  Adelanto ya pagado   14386 non-null  object
 16  Número de noches     14386 non-null  int64
 17  Estado               14386 non-null  object
 18  Huésped_Token        14386 non-null  object
 19  Teléfono_Token       14386 non-null  object
 20  Email_Token          14386 non-null  object
 21  Numero_Reserva       10427 non-null  object
 22  Mensaje_Huesped      10419 non-null  object
 23  BOOKING_NOTE         10419 non-null  object
 24  GENIUS               14386 non-null  bool
dtypes: bool(1), datetime64[ns](3), float64(4), int64(2), object(15)
memory usage: 2.8+ MB

In [69]:
#Comprobamos la extracción de datos del campo Notas del original
# Mostrar el DataFrame modificado de una reserva al azar (linea 100)
print("\nDataFrame NO modificado:")
print(combined_source_df_cleaned['Notas'][999])
print("\nNuevas columnas:")
print("\nBooking Note:")
print(combined_source_df_cleaned['BOOKING_NOTE'][999])
print("\nNumero_Reserva:")
print(combined_source_df_cleaned['Numero_Reserva'][999])
print("\nMensaje del Huesped:")
print(combined_source_df_cleaned['Mensaje_Huesped'][999])
print('\nGENIUS:')
print(combined_source_df_cleaned['GENIUS'][999])

DataFrame NO modificado:
Número de reserva: 3880677067
Mensaje del huésped: ** THIS RESERVATION HAS BEEN PRE-PAID **
BOOKING NOTE : Payment charge is EUR 1.122

Más información: booker_is_genius
Pago por adelantado: 102.00EUR

Nuevas columnas:

Booking Note:
Payment charge is EUR 1.122

Numero_Reserva:
3880677067

Mensaje del Huesped:


GENIUS:
True

In [70]:
# Mostrar los valores únicos en la columna 'Pagado'
print(combined_source_df_cleaned['Pagado'].unique())
# Convertir la columna booleana 'Pagado' a tipo objeto (texto)
combined_source_df_cleaned['Pagado'] = combined_source_df_cleaned['Pagado'].astype(str)
print(combined_source_df_cleaned['Pagado'].head())

['Sí' 'No']
13    Sí
15    Sí
16    No
17    Sí
18    No
Name: Pagado, dtype: object

# NUMERO DE HUESPEDES
## Creamos una columna "Numero de Huéspedes" sumando los adultos y los niños.
## Me aseguro de que los valores nulos (NaN) en 'Adultos' y 'Niños' sean tratados correctamente antes de la suma.
## Los reemplazamos con 0 si es necesario.

In [71]:
# Creamos una columna "Numero de Huéspedes" sumando los adultos y los niños.
# Me aseguro de que los valores nulos (NaN) en 'Adultos' y 'Niños' sean tratados correctamente antes de la suma.
# Los reemplazamos con 0 si es necesario.

combined_source_df_cleaned['Adultos'].fillna(0, inplace=True)
combined_source_df_cleaned['Niños'].fillna(0, inplace=True)

# Crear la nueva columna 'Numero_Clientes' sumando 'Adultos' y 'Niños'
combined_source_df_cleaned['Numero_Huespedes'] = combined_source_df_cleaned['Adultos'] + combined_source_df_cleaned['Niños']

C:\Users\jazpi\AppData\Local\Temp\ipykernel_21800\683601818.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  combined_source_df_cleaned['Adultos'].fillna(0, inplace=True)
C:\Users\jazpi\AppData\Local\Temp\ipykernel_21800\683601818.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  combined_source_df_cleaned['Niños'].fillna(0, inplace=True)

# LEAD TIME
## Creamos una columna "Lead Time" restando la fecha de reserva 'Creado' y la fecha de entrad 'Llegada'.

In [72]:

# Crear la nueva columna 'Lead_Time' restando 'Creado' menos 'Llegada'
combined_source_df_cleaned['Lead_Time'] = combined_source_df_cleaned['Creado'] - combined_source_df_cleaned['Llegada']
combined_source_df_cleaned['Lead_Time'].describe()

count                          14386
mean     -9 days +19:00:01.705825108
std       94 days 08:38:44.117280607
min              -433 days +23:26:00
25%               -33 days +01:04:00
50%                -2 days +09:43:30
75%                  0 days 15:48:00
max                334 days 12:44:00
Name: Lead_Time, dtype: object

# PRECIO DIARIO - DAILY RATE
## Quiero crear una nueva columna 'ADR' que se calcule en base al 'Precio' dividido entre la columna de 'Número de Noches'

In [73]:
# Verifica los tipos de datos de las columnas
print(combined_source_df_cleaned[['Precio', 'Número de noches']].dtypes)

# Comprueba si hay valores nulos en estas columnas
print(combined_source_df_cleaned[['Precio', 'Número de noches']].isnull().sum())

Precio              float64
Número de noches      int64
dtype: object
Precio              145
Número de noches      0
dtype: int64

In [74]:
condicion4 = combined_source_df_cleaned['Precio'].isna() == True
# Filtrar las filas que cumplen con la condición
filas_a_eliminar = combined_source_df_cleaned[condicion4]

# Crear un DataFrame excluyendo las filas que cumplen la condición
combined_source_df_cleaned_sin_filas = combined_source_df_cleaned.loc[~combined_source_df_cleaned.index.isin(filas_a_eliminar.index)]

# Verifica el resultado
print(combined_source_df_cleaned_sin_filas.head())

    Posición    Llegada     Salida     Apartamento Portal de reserva  \
13  32474470 2022-12-30 2023-01-01    H BMA MONACO       Booking.com
15  32470780 2022-12-30 2022-12-31  H BMA HELSINKI       Booking.com
17  32407618 2022-12-31 2023-01-01    H BMA DUBLIN       Booking.com
18  32401555 2022-12-28 2022-12-30     HD-GARAJE 5   Reserva directa
19  32400367 2022-12-31 2023-01-01        HD DARIO       Booking.com

                Creado  Adultos  Niños Check-in Check-out  ...     Estado  \
13 2022-12-30 15:16:00      1.0    1.0      NaN       NaN  ...  Reservado
15 2022-12-30 13:38:00      2.0    0.0      NaN       NaN  ...  Reservado
17 2022-12-28 20:36:00      4.0    0.0      NaN       NaN  ...  Reservado
18 2022-12-28 18:20:00      0.0    0.0      NaN       NaN  ...  Reservado
19 2022-12-28 17:53:00      2.0    0.0    16:00     11:00  ...  Reservado

                           Huésped_Token  \
13  165b0a32-f0de-472f-91b0-f4db1a5de1e9
15  f37086d0-e2ed-4564-af38-1a5c9babff7f
17  48fb4129-e9c0-4401-aa99-fbbbcf2903b2
18  f4289cb9-3b56-40f4-b80f-d4c04432ebcb
19  78732d24-e54b-4ea9-9eca-d1158595b81b

                          Teléfono_Token  \
13  ac05586d-fcf0-48c9-951a-a543d2b662d9
15  09f22c11-951f-4154-a498-457caca71a3e
17  c697a2e4-6368-4a79-9616-3780ec063f6b
18  9a35c9a1-ed21-4b64-a5fc-550221e3c822
19  92f00d29-f5bc-4383-a4d5-9d8bd4fb7f5c

                             Email_Token Numero_Reserva Mensaje_Huesped  \
13  9f635b58-7a19-4339-95bf-43a633fb37c0     3509184945
15  0407639f-425f-4566-8ef3-5958633ba344     3677697588
17  777a9013-c353-4b3c-895b-ac80e028c801     2331981900
18  558387d5-bf34-4d7c-90a4-45fc11a2918a            NaN             NaN
19  a2a89501-7d53-41d8-9665-cdb40cd2629d     3390950867

                    BOOKING_NOTE GENIUS Numero_Huespedes         Lead_Time
13  Payment charge is EUR 2.5839   True              2.0   0 days 15:16:00
15   Payment charge is EUR 1.045   True              2.0   0 days 13:38:00
17   Payment charge is EUR 2.695   True              4.0 -3 days +20:36:00
18                           NaN  False              0.0   0 days 18:20:00
19   Payment charge is EUR 2.211   True              2.0 -3 days +17:53:00

[5 rows x 27 columns]

In [75]:
# Asegúrate de que no haya división por cero
combined_source_df_cleaned['Número de noches'] = combined_source_df_cleaned['Número de noches'].replace(0, pd.NA)

# Crear la columna 'ADR'
combined_source_df_cleaned['ADR'] = combined_source_df_cleaned['Precio'] / combined_source_df_cleaned['Número de noches']

# Opcional: Reemplazar NaN en 'ADR' si hay valores de 'Número de Noches' que eran 0
combined_source_df_cleaned['ADR'] = combined_source_df_cleaned['ADR'].fillna(0)

# Verifica el resultado
print(combined_source_df_cleaned[['Precio', 'ADR']].head())

    Precio     ADR
13   234.9  117.45
15    95.0   95.00
16     NaN    0.00
17   245.0  245.00
18    40.0   20.00

In [76]:
print(combined_source_df_cleaned['ADR'].describe())

count    14386.000000
mean       122.610006
std         83.106241
min          0.000000
25%         70.000000
50%        101.000000
75%        157.550000
max       1502.700000
Name: ADR, dtype: float64

In [77]:
# Calcular el precio medio histórico para cada 'Apartamento' y 'Llegada'
historical_avg_price = combined_source_df_cleaned.groupby(['Apartamento', 'Llegada'])['Precio'].mean().reset_index()

# Renombrar la columna del precio medio
historical_avg_price.rename(columns={'Precio': 'Precio_Medio_Historico'}, inplace=True)

# Realizar el merge con el DataFrame original
combined_source_df_cleaned = combined_source_df_cleaned.merge(
    historical_avg_price, 
    on=['Apartamento', 'Llegada'], 
    how='left',
    suffixes=('', '_historico')  # Añadir sufijo para evitar conflictos
)

In [78]:
# Calcular el precio medio histórico excluyendo la reserva actual
historical_avg_price = combined_source_df_cleaned.apply(
    lambda row: combined_source_df_cleaned[
        (combined_source_df_cleaned['Apartamento'] == row['Apartamento']) & 
        (combined_source_df_cleaned['Llegada'] < row['Llegada'])
    ]['ADR'].mean(), 
    axis=1
)

# Añadir la columna calculada al DataFrame
combined_source_df_cleaned['Precio_Medio_Historico'] = historical_avg_price

In [79]:
combined_source_df_cleaned[['Apartamento', 'Precio', 'Número de noches', 'ADR', 'Precio_Medio_Historico']]

,Apartamento,Precio,Número de noches,ADR,Precio_Medio_Historico
0,H BMA MONACO,234.90,2,117.45,110.427971
1,H BMA HELSINKI,95.00,1,95.00,111.276875
2,H BMA GARAJE,NaN,4,0.00,19.459700
3,H BMA DUBLIN,245.00,1,245.00,121.511303
4,HD-GARAJE 5,40.00,2,20.00,14.154531
...,...,...,...,...,...
14381,H - BUA 3P,520.00,4,130.00,84.024558
14382,H BMA AMSTERDAM,159.25,1,159.25,240.824767
14383,H BMA BERLIN,521.60,2,260.80,163.806629
14384,H BMA AMSTERDAM,671.80,2,335.90,241.218314
14385,HG0 MUGARRA,261.80,2,130.90,182.386070

# OCUPACION del MES
## Quiero crear una nueva columna 'Ocupacion' en el que se muestra el porcentaje de unidades reservadas ese día.

In [80]:
# Crear un DataFrame para las fechas ocupadas
ocupacion = pd.DataFrame()

# Generar una serie de fechas ocupadas para cada reserva
for idx, row in combined_source_df_cleaned.iterrows():
    fechas_ocupadas = pd.date_range(start=row['Llegada'], end=row['Salida'] - pd.Timedelta(days=1), freq='D')
    df_temp = pd.DataFrame({
        'Fecha': fechas_ocupadas,
        'Apartamento': row['Apartamento']
    })
    ocupacion = pd.concat([ocupacion, df_temp], ignore_index=True)

# Calcular el número total de apartamentos (únicos)
total_apartamentos = combined_source_df_cleaned['Apartamento'].nunique()

# Contar el número de apartamentos ocupados por día
ocupacion_diaria = ocupacion.groupby('Fecha')['Apartamento'].nunique().reset_index()
ocupacion_diaria.rename(columns={'Apartamento': 'Apartamentos_Ocupados'}, inplace=True)

# Calcular el porcentaje de ocupación
ocupacion_diaria['Porcentaje_Ocupacion'] = (ocupacion_diaria['Apartamentos_Ocupados'] / total_apartamentos) * 100

# Mergear con el DataFrame original si es necesario
combined_source_df_cleaned = combined_source_df_cleaned.merge(
    ocupacion_diaria, 
    left_on='Llegada', 
    right_on='Fecha', 
    how='left'
)

In [81]:
combined_source_df_cleaned[['Llegada','Apartamento', 'Precio', 'Número de noches', 'ADR', 'Precio_Medio_Historico','Porcentaje_Ocupacion']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14386 entries, 0 to 14385
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Llegada                 14386 non-null  datetime64[ns]
 1   Apartamento             14386 non-null  object
 2   Precio                  14241 non-null  float64
 3   Número de noches        14386 non-null  int64
 4   ADR                     14386 non-null  float64
 5   Precio_Medio_Historico  14345 non-null  float64
 6   Porcentaje_Ocupacion    14353 non-null  float64
dtypes: datetime64[ns](1), float64(4), int64(1), object(1)
memory usage: 786.9+ KB

In [82]:
# Eliminar filas solo si tienen valores NaN en las columnas 'Precio', 'Precio_Medio_Historico' o 'Porcentaje_Ocupacion'
combined_source_df_cleaned = combined_source_df_cleaned.dropna(subset=['Precio', 'Precio_Medio_Historico', 'Porcentaje_Ocupacion'])


# Reemplazar todos los valores de la columna 'Check-in' con '16:00'
combined_source_df_cleaned['Check-in'] = '16:00'

# Reemplazar todos los valores de la columna 'Check-out' con '11:00'
combined_source_df_cleaned['Check-out'] = '11:00'

# Verificar el resultado
print(combined_source_df_cleaned[['Check-in','Check-out']])

# Verificar el resultado
print(combined_source_df_cleaned.info())

      Check-in Check-out
0        16:00     11:00
1        16:00     11:00
3        16:00     11:00
4        16:00     11:00
5        16:00     11:00
...        ...       ...
14381    16:00     11:00
14382    16:00     11:00
14383    16:00     11:00
14384    16:00     11:00
14385    16:00     11:00

[14170 rows x 2 columns]
<class 'pandas.core.frame.DataFrame'>
Index: 14170 entries, 0 to 14385
Data columns (total 32 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Posición                14170 non-null  int64
 1   Llegada                 14170 non-null  datetime64[ns]
 2   Salida                  14170 non-null  datetime64[ns]
 3   Apartamento             14170 non-null  object
 4   Portal de reserva       14170 non-null  object
 5   Creado                  14170 non-null  datetime64[ns]
 6   Adultos                 14170 non-null  float64
 7   Niños                   14170 non-null  float64
 8   Check-in                14170 non-null  object
 9   Check-out               14170 non-null  object
 10  Notas                   13352 non-null  object
 11  Precio                  14170 non-null  float64
 12  Detalles de precios     12585 non-null  object
 13  Comisión incluida       14170 non-null  float64
 14  Pagado                  14170 non-null  object
 15  Adelanto ya pagado      14170 non-null  object
 16  Número de noches        14170 non-null  int64
 17  Estado                  14170 non-null  object
 18  Huésped_Token           14170 non-null  object
 19  Teléfono_Token          14170 non-null  object
 20  Email_Token             14170 non-null  object
 21  Numero_Reserva          10375 non-null  object
 22  Mensaje_Huesped         10368 non-null  object
 23  BOOKING_NOTE            10368 non-null  object
 24  GENIUS                  14170 non-null  bool
 25  Numero_Huespedes        14170 non-null  float64
 26  Lead_Time               14170 non-null  timedelta64[ns]
 27  ADR                     14170 non-null  float64
 28  Precio_Medio_Historico  14170 non-null  float64
 29  Fecha                   14170 non-null  datetime64[ns]
 30  Apartamentos_Ocupados   14170 non-null  float64
 31  Porcentaje_Ocupacion    14170 non-null  float64
dtypes: bool(1), datetime64[ns](4), float64(9), int64(2), object(15), timedelta64[ns](1)
memory usage: 3.5+ MB
None

In [83]:
combined_source_df_cleaned[['Llegada','Apartamento', 'Precio', 'Número de noches', 'ADR', 'Precio_Medio_Historico','Porcentaje_Ocupacion']].head()

,Llegada,Apartamento,Precio,Número de noches,ADR,Precio_Medio_Historico,Porcentaje_Ocupacion
0,2022-12-30,H BMA MONACO,234.9,2,117.45,110.427971,29.268293
1,2022-12-30,H BMA HELSINKI,95.0,1,95.00,111.276875,29.268293
3,2022-12-31,H BMA DUBLIN,245.0,1,245.00,121.511303,39.024390
4,2022-12-28,HD-GARAJE 5,40.0,2,20.00,14.154531,51.219512
5,2022-12-31,HD DARIO,201.0,1,201.00,108.699008,39.024390

In [84]:
combined_source_df_cleaned[['Llegada','Apartamento', 'Precio', 'Número de noches', 'ADR', 'Precio_Medio_Historico','Porcentaje_Ocupacion']].describe()

,Llegada,Precio,Número de noches,ADR,Precio_Medio_Historico,Porcentaje_Ocupacion
count,14170,14170.000000,14170.000000,14170.000000,14170.000000,14170.000000
mean,2023-07-02 12:03:51.700776192,230.071982,1.816161,123.862298,114.359994,75.692549
min,2022-01-01 00:00:00,1.150000,1.000000,1.150000,10.000000,9.756098
25%,2022-11-04 00:00:00,82.000000,1.000000,71.000000,96.583300,56.097561
50%,2023-07-17 00:00:00,148.000000,1.000000,102.000000,110.495091,75.609756
75%,2024-03-07 00:00:00,272.000000,2.000000,158.333333,123.437877,97.560976
max,2024-12-07 00:00:00,7847.600000,81.000000,1502.700000,331.666667,100.000000
std,NaN,291.796386,1.950443,82.565860,41.017779,17.115534

In [85]:
combined_source_df_cleaned.describe()

,Posición,Llegada,Salida,Creado,Adultos,Niños,Precio,Comisión incluida,Número de noches,Numero_Huespedes,Lead_Time,ADR,Precio_Medio_Historico,Fecha,Apartamentos_Ocupados,Porcentaje_Ocupacion
count,1.417000e+04,14170,14170,14170,14170.000000,14170.000000,14170.000000,14170.000000,14170.000000,14170.000000,14170,14170.000000,14170.000000,14170,14170.000000,14170.000000
mean,4.253946e+07,2023-07-02 12:03:51.700776192,2023-07-04 17:40:07.960480256,2023-06-24 12:09:39.561044736,2.463726,0.360762,230.071982,31.099969,1.816161,2.824488,-8 days +00:05:47.860268173,123.862298,114.359994,2023-07-02 12:03:51.700776192,31.033945,75.692549
min,1.539014e+07,2022-01-01 00:00:00,2022-01-02 00:00:00,2021-02-12 11:22:00,0.000000,0.000000,1.150000,0.000000,1.000000,0.000000,-433 days +23:26:00,1.150000,10.000000,2022-01-01 00:00:00,4.000000,9.756098
25%,2.989671e+07,2022-11-04 00:00:00,2022-11-05 00:00:00,2022-10-25 22:17:00,2.000000,0.000000,82.000000,10.650000,1.000000,2.000000,-33 days +11:08:45,71.000000,96.583300,2022-11-04 00:00:00,23.000000,56.097561
50%,4.215626e+07,2023-07-17 00:00:00,2023-07-22 00:00:00,2023-07-03 11:11:30,2.000000,0.000000,148.000000,20.535000,1.000000,3.000000,-2 days +10:02:30,102.000000,110.495091,2023-07-17 00:00:00,31.000000,75.609756
75%,5.392231e+07,2024-03-07 00:00:00,2024-03-13 00:00:00,2024-02-22 16:19:00,3.000000,0.000000,272.000000,38.340000,2.000000,4.000000,0 days 15:49:45,158.333333,123.437877,2024-03-07 00:00:00,40.000000,97.560976
max,6.985467e+07,2024-12-07 00:00:00,2024-12-08 00:00:00,2024-12-08 23:16:00,8.000000,7.000000,7847.600000,867.750000,81.000000,8.000000,334 days 12:44:00,1502.700000,331.666667,2024-12-07 00:00:00,41.000000,100.000000
std,1.435905e+07,NaN,NaN,NaN,1.482575,0.782050,291.796386,37.941852,1.950443,1.639560,94 days 09:46:11.870985077,82.565860,41.017779,NaN,7.017369,17.115534

In [86]:
# Guardar el DataFrame en un archivo CSV en la carpeta 'data/02_processed/'
output_path = '../01_data/02_processed/df_final_modelar.csv'
# Guardar el DataFrame en un archivo CSV en la carpeta '02_processed/'
combined_source_df_cleaned.to_csv(output_path, index=False)

print(f"DataFrame guardado en {output_path}")

DataFrame guardado en ../01_data/02_processed/df_final_modelar.csv

In [89]:
df_num = combined_source_df_cleaned.select_dtypes(include = ['float64', 'int64'])
df_num.hist(figsize=(16, 20), bins=40, xlabelsize=6, ylabelsize=6)

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.

In [88]:
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
sns.histplot(combined_source_df_cleaned['Número de noches'].dropna(), bins=30, kde=False, color='blue')

ImportError: DLL load failed while importing _c_internal_utils: No se puede encontrar el módulo especificado.

In [ ]:
Outlier = combined_source_df_cleaned[combined_source_df_cleaned['Número de noches'] >= 360]
Outlier

Empty DataFrame
Columns: [Posición, Llegada, Salida, Apartamento, Portal de reserva, Creado, Adultos, Niños, Check-in, Check-out, Notas, Precio, Detalles de precios, Comisión incluida, Pagado, Adelanto ya pagado, Número de noches, Estado, Teléfono_Token, Email_Token, Numero_Reserva, Mensaje_Huesped, BOOKING_NOTE, GENIUS, Numero_Huespedes, Lead_Time]
Index: []

[0 rows x 26 columns]

In [ ]:
from ydata_profiling import ProfileReport


# Generar el perfilado del DataFrame
profile = ProfileReport(combined_source_df_cleaned, title="Análisis Exploratorio de Datos", explorative=True)

# Intentar mostrar el informe en el notebook
try:
    profile.to_notebook_iframe()
except Exception as e:
    print(f"Error al mostrar el informe en el notebook: {e}")

# Guardar el informe en un archivo HTML
profile.to_file("analisis_eda_cleaned.html")

ImportError: DLL load failed while importing _c_internal_utils: No se puede encontrar el módulo especificado.

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

# Verifica los tipos de datos y valores únicos para asegurar que 'Apartamento' y 'Creado' sean correctos
print(combined_source_df[['Creado', 'Apartamento']].dtypes)
print(combined_source_df['Apartamento'].unique())

# Crear histograma con diferentes líneas para cada categoría
plt.figure(figsize=(10, 6))

# Verifica si 'Creado' es un datetime y si no, conviértelo
if not pd.api.types.is_datetime64_any_dtype(combined_source_df['Creado']):
    combined_source_df['Creado'] = pd.to_datetime(combined_source_df['Creado'], errors='coerce')

# Crear el histograma
sns.histplot(data=combined_source_df, x='Creado', hue='Apartamento', multiple='stack', kde=True)

# Personalizar el gráfico
plt.title('Evolución de Precio por Apartamento')
plt.xlabel('Creado')
plt.ylabel('Precio')

# Asegurarse de que la leyenda se muestra correctamente
plt.legend(title='Apartamento', bbox_to_anchor=(1.05, 1), loc='upper left')

# Mostrar el gráfico
plt.tight_layout()
plt.show()

Creado         datetime64[ns]
Apartamento            object
dtype: object
['HD OLIVIA' 'HD FIDEL' 'HD ALEJANDRA' 'H BMA LISBOA' 'HD HUGHET'
 'HD GLORIA' 'HD DARIO' 'HD CELESTE' 'H BMA BERLIN' 'H BMA MONACO'
 'H BMA HELSINKI' 'H BMA GARAJE' 'H BMA DUBLIN' 'HD-GARAJE 5'
 'H BMA AMSTERDAM' 'H BMA CHICAGO' 'HD ELENA' 'H - BUA GARAJE'
 'H - BUA 3P' 'H BMA PRAGA' 'H - BUA 4P' 'HD BRUNO' 'H BMA OSLO'
 'HG0 COBETAS' 'HG0 PAGASARRI' 'HG1 ARRAIZ' 'HG0 GANEKOGORTA' 'HG1 AMBOTO'
 'HG1 ARTXANDA' 'HG0 MUGARRA' 'HG0 GANETA' 'AH11 DOBLE ARIAS'
 'AH10 INDIVIDUAL ARIAS' 'AH2 DOBLE ARIAS' 'AH12 DOBLE ARIAS'
 'AH1 DOBLE ARIAS' 'AH6 INDIVIDUAL ARIAS' 'AH14 INDIVIDUAL ARIAS'
 'AH13 INDIVIDUAL ARIAS' 'AH9 DOBLE ARIAS' 'AH4 INDIVIDUAL ARIAS']

C:\Users\jazpi\AppData\Local\Temp\ipykernel_32524\3645192834.py:24: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  plt.legend(title='Apartamento', bbox_to_anchor=(1.05, 1), loc='upper left')
C:\Users\jazpi\AppData\Local\Temp\ipykernel_32524\3645192834.py:28: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()